# GenAI Toolkit Configuration
# Basic configuration for running tests, Agents and CLI commands

paths:
  home: ${oc.env:HOME}
  project: ${oc.env:PWD}
  config: ${paths.project}/config

merge:
  - ${paths.config}/baseline.yaml
  - ${paths.config}/overrides.yaml
  - ${paths.config}/mcp_servers.yaml
 

# Command Line Interface configuration
cli:
  commands:  # List modules:functions to register CLI commands
    - genai_tk.main.commands_core:register_commands
    - genai_tk.main.commands_extra:register_commands
    - genai_tk.main.commands_agents:register_commands
    - genai_tk.main.cli:register_commands

# Logging configuration
logging:
  level: "INFO"

# Other test configurations
test:
  timeout: 30

