
# AI Components
llm:
  list: config/providers/llm.yaml
  models:
    default: gpt_41mini_openai  
    fake: parrot_local_fake 
  cache: sqlite
  cache_path: data/llm_cache/langchain.db

embeddings:
  list: config/providers/embeddings.yaml
  models:
    default: ada_002_openai
    local: artic_22_ollama
    fake: embeddings_768_fake  # For testing
  cache: data/hf_models

vector_store:
  default: InMemory

# Key-Value Store configuration
kv_store:
  engine: "memory"  # Use memory store for tests
  
# LLM Cache configuration  
llm_cache:
  method: "memory"  # Use memory cache for tests