rag_configs:
   basic_in_memory:
      vector_store:
         id: InMemory
         index: True
      embeddings:
         id: default
         cache: True
      text_splitter: 
         class: RecursiveCharacterTextSplitter 
         chunk_size: 200

